2025-08-13 05:33:35,405 WARNING google_languages Warning: Egyptian Arabic not found in the database for group Arabic.
2025-08-13 05:33:35,734 INFO signals Successfully created language preferences for user testuser (ID: 4)
2025-08-13 05:33:35,740 ERROR middleware Exception: Book ({'id': 999}) not found
Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/models.py", line 291, in get_if_can_be_read
    book = cls.objects.get(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
lexiflux.models.Book.DoesNotExist: Book matching query does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/decorators.py", line 44, in wrapper
    return login_required(view_func)(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/views/library_views.py", line 84, in dispatch
    self.book = Book.get_if_can_be_read(request.user, id=kwargs.get("book_id"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/models.py", line 295, in get_if_can_be_read
    raise ObjectDoesNotExist(f"Book ({kwargs}) not found") from e
django.core.exceptions.ObjectDoesNotExist: Book ({'id': 999}) not found
2025-08-13 05:33:35,741 WARNING log Bad Request: /modals/edit-book/999/
2025-08-13 05:33:35,741 WARNING log Bad Request: /modals/edit-book/999/
