2025-08-13 05:34:14,026 ERROR import_views Error importing book
Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/views/import_views.py", line 169, in import_url
    validator(url)
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/core/validators.py", line 171, in __call__
    raise ValidationError(self.message, code=self.code, params={"value": value})
django.core.exceptions.ValidationError: ['Enter a valid URL.']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/views/import_views.py", line 47, in import_book
    book = import_url(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/views/import_views.py", line 171, in import_url
    raise ValueError("Invalid URL format") from e
ValueError: Invalid URL format
